// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Ligi.Infrastructure.Sql.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Add_League_Season_Fixture_Tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_League_Season_Fixture_Tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201312201158468_Add_League_Season_Fixture_Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
