// <auto-generated />
namespace Ligi.Infrastructure.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddedHomeAndAwayTeamNavProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedHomeAndAwayTeamNavProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201401101243093_AddedHomeAndAwayTeamNavProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
